plugins {
    id("com.android.application") version "8.5.2" apply false
}

allprojects {
    repositories {
        maven { url "https://maven.aliyun.com/repository/google" }
        maven { url "https://maven.aliyun.com/repository/public" }
        google()
        mavenCentral()
    }
}

tasks.register("clean", Delete) {
    delete(rootProject.layout.buildDirectory)
}